before_script:
  - sudo apt-get install -y unzip
  - curl -k -L -O https://github.com/downloads/webmetrics/browsermob-proxy/browsermob-proxy-2.0-beta-3-bin.zip
  - unzip browsermob-proxy-2.0-beta-3-bin.zip
  - ln -s `pwd`/browsermob-proxy-2.0-beta-3 /tmp/browsermob-proxy
  - sh -e /etc/init.d/xvfb start
